### ISSUE TITLE
Problem in Linux Profile

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/community#21] opened 2017-03-28 12:25 UTC
hello everyone ,

- friends I'm facing one problem with volatility version 2.6 can you people please help me.
    +  problem is : volatility come with default windows profiles but there is no any Linux profile to resolve this problem there is a already some prebuilt Linux profile is available _https://github.com/volatilityfoundation/profiles_ i follow this instructions but still i'm not geting profile in profile list after performing "python vol.py image info -f /dump/victoria-v8.memdump.img" 

+ i follow this solution but it's not work for me in volatility version 2.6

**Comment by gleeda** [comment] 2017-03-28 20:54
Duplicate of issue https://github.com/volatilityfoundation/profiles/issues/41

**Closed as completed by gleeda** 2017-03-28 20:54 UTC
