### ISSUE TITLE
volatility plugin

### ISSUE THREAD

**Issue by SawsanAlodibat** [volatilityfoundation/community#20] opened 2017-02-27 11:17 UTC
when I'm trying to run the following command on win 10:

volatility_2.6_win64_standalone.exe --plugins=myplugins --profile=Win10x64 -f 20170224.mem myplugin
I get this error:

Traceback (most recent call last):
File "vol.py", line 192, in 
File "vol.py", line 183, in main
File "volatility\commands.py", line 147, in execute
File "volatility\commands.py", line 282, in render_text
File "volatility\commands.py", line 273, in _render
File "volatility\commands.py", line 270, in unified_output
NotImplementedError: Rendering using the unified output format has not been implemented for this plugin.
Failed to execute script vol

**Comment by gleeda** [comment] 2017-03-28 20:55
duplicate of issue volatilityfoundation/volatility#379

**Closed as completed by gleeda** 2017-03-28 20:55 UTC
